networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1

services:
  simulator:
    image: jkayembe/simulator:latest
    container_name: simulator
    networks:
      my-network:
        ipv4_address: 172.19.0.2
    ports:
      - "5900:5900"  # VNC port
    environment:
      IS_MEASURED: "false"
      SEED: "123"
    volumes:
      - ./entrypoint.sh:/app/entrypoint.sh  # Mount the entrypoint script
      - ./src:/app/src  # Mount simulator
      - ./scenarios_2025:/app/scenarios_2025  # Mount the scenarios directory
      - ./emails_answers:/app/emails_answers  # Mount the emails answers directory
    working_dir: /app
    command: /app/entrypoint.sh