name: Email Session Test
author: Jason Kayembe
description: This test launches an email session scenario

services:
    simulator:
        image: jkayembe/simulator:latest
        ports:
            - 5900:5900
        environment:
          IS_MEASURED: "true"
          SEED: 123
        shell: "bash"
        folder-destination: "/mount_point"
        setup-commands:

            # Copy the setup and entrypoint scripts and the source code from /mount_point to the container's app/ folder
            # The GMT doesn't allow to write in mounted volumes (which is /mount_point here).
            - echo "Copying entrypoint script and source code to /app directory"
            - cp /mount_point/setup.sh /app/
            - cp /mount_point/entrypoint.sh /app/
            - cp -R /mount_point/src/ /app/
            - cp -R /mount_point/scenarios_2025/ /app/
            - cp -R /mount_point/emails_answers/ /app/

            # Configure the container with the entrypoint script
            # [--use-host-as-dns] : Use this if Pi-Hole is running on host. Remove if no DNS service is running on host
            # [--send-gui-to-vnc] : Use this if you want to send the GUI to a VNC server.
            - echo "Configuring the container with the entrypoint script"
            - /app/setup.sh
              --use-host-as-dns
              #--send-gui-to-vnc

        command: "bash"

flow:
    - name: Run the scenario
      container: simulator
      commands:
        - type: console
          command: /app/entrypoint.sh
          note: Starting the Python Scenario Script
          log-stdout: true
          read-notes-stdout: true # This is needed for the GMT to save the logs along with their timestamps. This will later be used to map energy and traffic data to specific events in the scenario.
