name: Email Session Test
author: Jason Kayembe
description: This test launches an email session scenario

services:
    simulator:
        image: jkayembe/simulator:latest
        ports:
            - 5900:5900
        environment:
          IS_MEASURED: "true"
          SEED: 123
        shell: "bash"
        setup-commands:
            # Change the chrome profile directory to avoid changing the backup profile folder
            - cp -R /app/chrome_profiles/ /chrome_profiles

            # Add host ip for my-solution.com and as the dns server (to use pihole adblocker as dns)
             # Extract the hexadecimal gateway IP
            - "GATEWAY_HEX=$(awk '$2 == \"00000000\" { print $3 }' /proc/net/route) ;
               GATEWAY_IP=$(printf \"%d.%d.%d.%d\n\"
               $((0x${GATEWAY_HEX:6:2}))
               $((0x${GATEWAY_HEX:4:2}))
               $((0x${GATEWAY_HEX:2:2}))
               $((0x${GATEWAY_HEX:0:2}))) ;
               echo \"$GATEWAY_IP my-solution.com\" >> /etc/hosts ;
               echo \"nameserver $GATEWAY_IP\" > /etc/resolv.conf "

            # X Server : simulate graphic card in memory. (The html pages are unpredictable in headless mode)
            - Xvfb :0 -screen 0 1296x736x16 & 

            # VNC server : It connects to the X server and send the GUI on port 5900. Uncomment the next line for Debugging
            #- x11vnc -forever -create -display :0 -rfbport 5900 -bg -nopw
        folder-destination: "/app"
        command: "bash"

flow:
    - name: Run the scenario
      container: simulator
      commands:
        - type: console
          command: python src/scenario.py scenarios_2025/2025_proton_session_adblock.json
          note: Starting the Python Scenario Script
          log-stdout: true
          read-notes-stdout: true # This is needed for the GMT to save the logs along with their timestamps. This will later be used to map energy and traffic data to specific events in the scenario.